# Generated by Django 5.1.3 on 2025-02-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long',
            field=models.URLField(unique=True),
        ),
    ]
