# Generated by Django 5.1.3 on 2025-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_url_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long',
            field=models.URLField(),
        ),
    ]
